//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS_Shop.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPosition
    {
        public int OrderPositionId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Product_ProductId { get; set; }
        public int Amount { get; set; }
        public decimal PurchasePrice { get; set; }
        public string ProductName { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
