// <auto-generated />
namespace LS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderpositionwithoutproductrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderpositionwithoutproductrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011028330_orderposition-without-product-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
