// <auto-generated />
namespace LS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class settingstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(settingstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011426389_settings-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
